<a href="https://colab.research.google.com/github/GonzaloAcost4/ADE2026_TpiUniversidad/blob/main/TP2/Sources/ADE_TP2_Analisis_de_los_datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Análisis de los datos por cada source
Solo para guiarme y saber que problemas tenemos :) por si les sirve.

*   Elemento de la lista
*   Elemento de la lista

In [1]:
import pandas as pd

In [2]:
dfCur = pd.read_csv('https://raw.githubusercontent.com/GonzaloAcost4/ADE2026_TpiUniversidad/refs/heads/main/TP2/Sources/curso.csv')
dfCurProg = pd.read_csv('https://raw.githubusercontent.com/GonzaloAcost4/ADE2026_TpiUniversidad/refs/heads/main/TP2/Sources/curso_programa.csv')
dfDep = pd.read_csv('https://raw.githubusercontent.com/GonzaloAcost4/ADE2026_TpiUniversidad/refs/heads/main/TP2/Sources/departamento.csv')
dfDic = pd.read_csv('https://raw.githubusercontent.com/GonzaloAcost4/ADE2026_TpiUniversidad/refs/heads/main/TP2/Sources/dictado.csv')
dfDoce = pd.read_csv('https://raw.githubusercontent.com/GonzaloAcost4/ADE2026_TpiUniversidad/refs/heads/main/TP2/Sources/docente.csv')
dfEst = pd.read_csv('https://raw.githubusercontent.com/GonzaloAcost4/ADE2026_TpiUniversidad/refs/heads/main/TP2/Sources/estudiante.csv')
dfEvaCur = pd.read_csv('https://raw.githubusercontent.com/GonzaloAcost4/ADE2026_TpiUniversidad/refs/heads/main/TP2/Sources/evaluacion_curso.csv')
dfEx = pd.read_csv('https://raw.githubusercontent.com/GonzaloAcost4/ADE2026_TpiUniversidad/refs/heads/main/TP2/Sources/examen.csv')
dfFac = pd.read_csv('https://raw.githubusercontent.com/GonzaloAcost4/ADE2026_TpiUniversidad/refs/heads/main/TP2/Sources/facultad.csv')
dfIns = pd.read_csv('https://raw.githubusercontent.com/GonzaloAcost4/ADE2026_TpiUniversidad/refs/heads/main/TP2/Sources/inscripcion.csv')
dfPro = pd.read_csv('https://raw.githubusercontent.com/GonzaloAcost4/ADE2026_TpiUniversidad/refs/heads/main/TP2/Sources/programa.csv')

## Estudiante:

In [3]:
dfEst.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 130000 entries, 0 to 129999
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id_estudiante     130000 non-null  int64
 1   dni               130000 non-null  object
 2   apellido          130000 non-null  object
 3   nombre            130000 non-null  object
 4   genero            130000 non-null  object
 5   fecha_nacimiento  130000 non-null  object
 6   email             126030 non-null  object
 7   telefono          123549 non-null  object
 8   nacionalidad      127264 non-null  object
 9   id_programa       130000 non-null  int64
 10  anio_ingreso      130000 non-null  int64
dtypes: int64(3), object(8)
memory usage: 10.9+ MB

* Dni es object.
* Email, telefono y nacionalidad tienen nulos.
* Datos requeridos: id_estudiante, dni, apellido, nombre, fecha_nacimiento, id_programa, anio_ingreso

### DNI

In [4]:
len(dfEst[(dfEst['dni'] == '') | (dfEst['dni'] == ' ')])

0

In [5]:
patrones = dfEst['dni'].astype(str).str.replace(r'\d', '#', regex=True)
print(patrones.value_counts())

dni
########      119501
 ########       5317
##.###.###      5182
Name: count, dtype: int64

In [6]:
dfEst['dni'].astype(str).str.strip().str.replace('.', '').str.len().value_counts()

dni
8    130000
Name: count, dtype: int64

In [22]:
conteo_dni = dfEst['dni'].value_counts()
conteo_dni[conteo_dni > 1].value_counts()

count
2    2387
3      81
4       6
Name: count, dtype: int64

### Genero

In [7]:
dfEst.genero.unique()

array(['M', 'F', '1', 'Femenino', 'male', '2', 'm', 'Masculino', 'female',
       'f'], dtype=object)

### Fecha_nacimiento

In [8]:
patronesFecha = dfEst['fecha_nacimiento'].astype(str).str.replace(r'\d', '#', regex=True)
print(patronesFecha.value_counts())

fecha_nacimiento
####-##-##    114462
##/##/####      5129
####            3894
##-##-####      3884
########        2631
Name: count, dtype: int64

### Nacionalidad

In [9]:
dfEst.nacionalidad.unique()

array(['Argentina', 'Chilena', 'Paraguaya', 'Brasileña', 'Venezolana',
       'Colombiana', 'Boliviana', 'Peruana', nan, 'Uruguaya'],
      dtype=object)

In [10]:
dfEst[dfEst['nacionalidad'].isna()][['id_estudiante', 'nacionalidad']]

        id_estudiante nacionalidad
104               105          NaN
138               139          NaN
197               198          NaN
212               213          NaN
229               230          NaN
...               ...          ...
129837         129838          NaN
129886         129887          NaN
129889         129890          NaN
129937         129938          NaN
129938         129939          NaN

[2736 rows x 2 columns]

* Hay que ver como tratar esto, agregar la clase "No especificado" o asumir que son Argentinos.

## Examen:

In [11]:
dfEx.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 890389 entries, 0 to 890388
Data columns (total 6 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   id_examen       890389 non-null  int64
 1   id_inscripcion  890389 non-null  int64
 2   fecha           890389 non-null  object
 3   nota            890389 non-null  float64
 4   numero_intento  890389 non-null  int64
 5   resultado       890389 non-null  object
dtypes: float64(1), int64(3), object(2)
memory usage: 40.8+ MB

* Datos requeridos: id_examen, id_inscripcion, fecha, nota.
* Hay que analizar que hacer con nro_intento, es requerido si o si? asumimos que si viene nulo es el 1ero?

In [12]:
patronesFecha = dfEx['fecha'].astype(str).str.replace(r'\d', '#', regex=True)
print(patronesFecha.value_counts())

fecha
####-##-##    890389
Name: count, dtype: int64

In [13]:
len(dfEx[(dfEx['nota']=='') | (dfEx['nota']==' ')])

0

In [18]:
dfEx.nota.max()

10.0

In [19]:
dfEx.nota.min()

1.0

In [17]:
dfEx.numero_intento.unique()

array([1, 2, 3])

In [14]:
dfEx.resultado.unique()

array(['Aprobado', 'Desaprobado'], dtype=object)

In [15]:
dfEx[dfEx['resultado'] == 'Desaprobado']['nota'].max()

3.9

In [16]:
dfEx[dfEx['resultado'] == 'Aprobado']['nota'].min()

4.0

* Hay aprobados con nota menor a 0

In [27]:
conteoEx = dfEx.groupby(['id_examen', 'id_inscripcion'])['numero_intento'].count()
conteoEx[conteoEx > 1].value_counts()

Series([], Name: count, dtype: int64)

In [23]:
dfEx.groupby(['id_examen', 'id_inscripcion'])['numero_intento'].count()

id_examen  id_inscripcion
1          1                 1
2          3                 1
3          4                 1
4          5                 1
5          5                 1
                            ..
890385     1003408           1
890386     1003409           1
890387     1003411           1
890388     1003412           1
890389     1003413           1
Name: numero_intento, Length: 890389, dtype: int64