<a href="https://colab.research.google.com/github/GonzaloAcost4/ADE2026_TpiUniversidad/blob/main/TP2/Sources/ADE_TP2_Analisis_de_los_datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Análisis de los datos por cada source
Solo para guiarme y saber que problemas tenemos :) por si les sirve.

In [1]:
import pandas as pd

In [2]:
dfCur = pd.read_csv('https://raw.githubusercontent.com/GonzaloAcost4/ADE2026_TpiUniversidad/refs/heads/main/TP2/Sources/curso.csv')
dfCurProg = pd.read_csv('https://raw.githubusercontent.com/GonzaloAcost4/ADE2026_TpiUniversidad/refs/heads/main/TP2/Sources/curso_programa.csv')
dfDep = pd.read_csv('https://raw.githubusercontent.com/GonzaloAcost4/ADE2026_TpiUniversidad/refs/heads/main/TP2/Sources/departamento.csv')
dfDic = pd.read_csv('https://raw.githubusercontent.com/GonzaloAcost4/ADE2026_TpiUniversidad/refs/heads/main/TP2/Sources/dictado.csv')
dfDoce = pd.read_csv('https://raw.githubusercontent.com/GonzaloAcost4/ADE2026_TpiUniversidad/refs/heads/main/TP2/Sources/docente.csv')
dfEst = pd.read_csv('https://raw.githubusercontent.com/GonzaloAcost4/ADE2026_TpiUniversidad/refs/heads/main/TP2/Sources/estudiante.csv')
dfEvaCur = pd.read_csv('https://raw.githubusercontent.com/GonzaloAcost4/ADE2026_TpiUniversidad/refs/heads/main/TP2/Sources/evaluacion_curso.csv')
dfEx = pd.read_csv('https://raw.githubusercontent.com/GonzaloAcost4/ADE2026_TpiUniversidad/refs/heads/main/TP2/Sources/examen.csv')
dfFac = pd.read_csv('https://raw.githubusercontent.com/GonzaloAcost4/ADE2026_TpiUniversidad/refs/heads/main/TP2/Sources/facultad.csv')
dfIns = pd.read_csv('https://raw.githubusercontent.com/GonzaloAcost4/ADE2026_TpiUniversidad/refs/heads/main/TP2/Sources/inscripcion.csv')
dfPro = pd.read_csv('https://raw.githubusercontent.com/GonzaloAcost4/ADE2026_TpiUniversidad/refs/heads/main/TP2/Sources/programa.csv')

## Estudiante:

In [3]:
dfEst.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 130000 entries, 0 to 129999
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id_estudiante     130000 non-null  int64
 1   dni               130000 non-null  object
 2   apellido          130000 non-null  object
 3   nombre            130000 non-null  object
 4   genero            130000 non-null  object
 5   fecha_nacimiento  130000 non-null  object
 6   email             126030 non-null  object
 7   telefono          123549 non-null  object
 8   nacionalidad      127264 non-null  object
 9   id_programa       130000 non-null  int64
 10  anio_ingreso      130000 non-null  int64
dtypes: int64(3), object(8)
memory usage: 10.9+ MB

* Dni es object.
* Email, telefono y nacionalidad tienen nulos.
* Datos requeridos: id_estudiante, dni, apellido, nombre, fecha_nacimiento, id_programa, anio_ingreso

### Nombre y Apellido

In [48]:
dfEst.nombre.unique()

array(['Agustín', 'Julián', 'Ezequiel', 'Natalia', 'Ignacio', 'Emilio',
       'Gonzalo', 'Martín', 'Cristian', 'Rodrigo', 'Nicolás', 'Diego',
       'Matías', 'Romina', 'leandro', 'Maximiliano', 'Tomás', 'Alejandra',
       'Cristian Cristian', 'Damián', 'Facundo', 'Gastón', 'Sebastián',
       'Luciana', 'Sergio', 'Vanesa', 'Hernán', 'Iván', 'Alejandro',
       'Leandro', 'Pablo', 'NOELIA', 'Lucas', 'Ignacio Ignacio', 'Laura',
       'Micaela', 'DAMIÁN', 'Federico', 'Santiago', 'Ramiro', 'Fernando',
       'cristian', 'Claudio', 'Soledad', 'IGNACIO', 'Patricia',
       'sebastián', 'Valentina', 'Mariela', 'cecilia', 'Andrea',
       'Sabrina', 'Mariana', 'Gabriela', 'Silvina', 'Noelia',
       'Tomás Tomás', 'Jimena', 'Gonzalo Gonzalo', 'Daniela', 'Paola',
       'Pablo Pablo', 'Cecilia', 'Valeria', 'CRISTIAN', 'LUCAS',
       'Claudia', 'Lucas Lucas', 'EZEQUIEL', 'rodrigo', 'MARIANA',
       'Maximiliano Maximiliano', 'Sofía', 'damián', 'Verónica Verónica',
       'MATÍAS', 'Hernán Hernán', 'Florencia', 'Gastón Gastón',
       'santiago', 'FLORENCIA', 'iván', 'RAMIRO', 'Camila', 'Verónica',
       'EMILIO', 'SOFÍA', 'Claudio Claudio', 'Federico Federico',
       'FEDERICO', 'ALEJANDRO', 'Iván Iván', 'AGUSTÍN', 'IVÁN',
       'SANTIAGO', 'SERGIO', 'Julián Julián', 'claudio', 'JULIÁN',
       'carolina', 'ALEJANDRA', 'ignacio', 'ezequiel', 'Noelia Noelia',
       'maximiliano', 'Carolina', 'fernando', 'facundo', 'emilio',
       'MAXIMILIANO', 'Micaela Micaela', 'Rodrigo Rodrigo',
       'Facundo Facundo', 'LAURA', 'SEBASTIÁN', 'PABLO', 'nicolás',
       'Valentina Valentina', 'Agustín Agustín', 'Matías Matías',
       'Damián Damián', 'Daniela Daniela', 'Emilio Emilio', 'CECILIA',
       'DANIELA', 'gastón', 'Ezequiel Ezequiel', 'Sofía Sofía', 'martín',
       'Nicolás Nicolás', 'tomás', 'natalia', 'Santiago Santiago',
       'daniela', 'lucas', 'jimena', 'FERNANDO', 'TOMÁS', 'GASTÓN',
       'NICOLÁS', 'pablo', 'LEANDRO', 'Mariela Mariela', 'gonzalo',
       'VALERIA', 'noelia', 'Soledad Soledad', 'Sergio Sergio',
       'CAROLINA', 'CLAUDIO', 'CAMILA', 'FACUNDO', 'Sabrina Sabrina',
       'matías', 'PAOLA', 'GONZALO', 'Gabriela Gabriela',
       'Mariana Mariana', 'Luciana Luciana', 'ROMINA', 'MARTÍN',
       'Patricia Patricia', 'HERNÁN', 'gabriela', 'Alejandro Alejandro',
       'SABRINA', 'Silvina Silvina', 'valentina', 'mariana', 'paola',
       'sofía', 'Cecilia Cecilia', 'Jimena Jimena', 'DIEGO', 'VANESA',
       'Valeria Valeria', 'Sebastián Sebastián', 'Martín Martín',
       'RODRIGO', 'Diego Diego', 'micaela', 'sergio', 'Laura Laura',
       'ANDREA', 'Paola Paola', 'Claudia Claudia', 'luciana', 'mariela',
       'Fernando Fernando', 'diego', 'CLAUDIA', 'agustín',
       'Leandro Leandro', 'federico', 'alejandro', 'Natalia Natalia',
       'patricia', 'andrea', 'silvina', 'Florencia Florencia', 'ramiro',
       'PATRICIA', 'MICAELA', 'Ramiro Ramiro', 'vanesa', 'VALENTINA',
       'julián', 'Carolina Carolina', 'Andrea Andrea', 'hernán',
       'Camila Camila', 'soledad', 'SOLEDAD', 'MARIELA', 'romina',
       'florencia', 'sabrina', 'JIMENA', 'Vanesa Vanesa', 'LUCIANA',
       'VERÓNICA', 'claudia', 'alejandra', 'GABRIELA', 'NATALIA',
       'camila', 'SILVINA', 'Alejandra Alejandra', 'valeria', 'verónica',
       'Romina Romina', 'laura'], dtype=object)

In [54]:
dfEst.apellido.unique()

array(['Flores', 'Ramírez', 'Quispe', 'Fernández', 'Romero', 'Pérez',
       'Herrera', 'Mendoza', 'fernández', 'Villalba', 'Vargas', 'Carrizo',
       'Rodríguez', 'Acosta', 'Morales', 'Torres', 'Sánchez', 'Flores  ',
       'Gómez', 'Vera', 'Medina', 'Ojeda', 'Peralta', 'Díaz', 'Molina',
       'Ortega', 'Suárez', 'Ramos', 'medina', 'Bogado', 'Cruz', 'Ledesma',
       'Ríos', 'López', 'Rojas', 'MORENO', 'Cabrera', 'Álvarez',
       'González', 'Mamani', 'Núñez', 'vargas', 'Lima', 'Martínez',
       'Fuentes', 'Reyes', 'Muñoz', 'Quispe  ', 'García', 'ROMERO',
       'Moreno', 'Ruiz', 'Huanca', 'GARCÍA', 'garcía', 'Souza', 'Castro',
       'gonzález', 'Oliveira', 'Santos', 'Benítez', 'Giménez', 'RUIZ',
       'Fuentes  ', 'Acosta  ', 'cabrera', 'ortega', 'Álvarez  ',
       'RAMÍREZ', 'Pereira', 'HERRERA', 'Vega', 'Condori', 'VERA',
       'CONDORI', 'VARGAS', 'CARRIZO', 'Apaza', 'ACOSTA', 'morales',
       'benítez', 'Silva', 'Santos  ', 'Sánchez  ', 'Molina  ', 'LEDESMA',
       'RODRÍGUEZ', 'CABRERA', 'Peralta  ', 'giménez', 'MEDINA',
       'Mendoza  ', 'bogado', 'MENDOZA', 'SUÁREZ', 'Medina  ', 'LÓPEZ',
       'fuentes', 'TORRES', 'lópez', 'PÉREZ', 'Suárez  ', 'moreno',
       'MORALES', 'HUANCA', 'OJEDA', 'santos', 'pereira', 'APAZA',
       'gómez', 'SOUZA', 'CRUZ', 'VILLALBA', 'pérez', 'NÚÑEZ', 'MOLINA',
       'López  ', 'SÁNCHEZ', 'Díaz  ', 'romero', 'ORTEGA', 'díaz',
       'PERALTA', 'FLORES', 'Muñoz  ', 'García  ', 'quispe', 'BOGADO',
       'PEREIRA', 'rodríguez', 'Silva  ', 'ÁLVAREZ', 'RÍOS', 'vega',
       'LIMA', 'Pérez  ', 'huanca', 'molina', 'MARTÍNEZ', 'ríos',
       'Gómez  ', 'vera', 'álvarez', 'Vargas  ', 'GÓMEZ', 'cruz',
       'Herrera  ', 'rojas', 'Oliveira  ', 'DÍAZ', 'Fernández  ', 'RAMOS',
       'mendoza', 'REYES', 'núñez', 'ROJAS', 'González  ', 'ruiz',
       'Rodríguez  ', 'SANTOS', 'GIMÉNEZ', 'GONZÁLEZ', 'reyes', 'FUENTES',
       'Núñez  ', 'Torres  ', 'ojeda', 'Pereira  ', 'BENÍTEZ', 'acosta',
       'torres', 'sánchez', 'Ledesma  ', 'Cabrera  ', 'Ojeda  ',
       'Martínez  ', 'ramírez', 'castro', 'Cruz  ', 'martínez',
       'Castro  ', 'oliveira', 'CASTRO', 'Vera  ', 'ledesma', 'Ríos  ',
       'lima', 'Rojas  ', 'souza', 'Mamani  ', 'Ramos  ', 'FERNÁNDEZ',
       'peralta', 'suárez', 'Ruiz  ', 'Ortega  ', 'Moreno  ', 'FUENTES  ',
       'VEGA', 'muñoz', 'Giménez  ', 'carrizo', 'SILVA', 'OJEDA  ',
       'ramos', 'Villalba  ', 'Carrizo  ', 'CARRIZO  ', 'Benítez  ',
       'herrera', 'QUISPE', 'Morales  ', 'MAMANI', 'Vega  ', 'OLIVEIRA',
       'flores', 'Reyes  ', 'Lima  ', 'Romero  ', 'mamani', 'Huanca  ',
       'Ramírez  ', 'villalba', 'ACOSTA  ', 'MUÑOZ', 'Condori  ',
       'Souza  ', 'condori', 'apaza', 'VEGA  ', 'Apaza  ', 'ORTEGA  ',
       'REYES  ', 'CRUZ  ', 'MORENO  ', 'Bogado  ', 'FLORES  ',
       'HERRERA  ', 'MENDOZA  ', 'silva', 'MARTÍNEZ  ', 'MAMANI  ',
       'MOLINA  ', 'VILLALBA  ', 'HUANCA  ', 'FERNÁNDEZ  ', 'QUISPE  ',
       'SANTOS  ', 'RAMOS  ', 'PÉREZ  ', 'PERALTA  ', 'ROJAS  ',
       'SUÁREZ  ', 'ROMERO  ', 'SÁNCHEZ  ', 'GIMÉNEZ  ', 'RODRÍGUEZ  ',
       'GONZÁLEZ  ', 'GÓMEZ  ', 'GARCÍA  ', 'RAMÍREZ  ', 'VERA  ',
       'CASTRO  '], dtype=object)

### DNI

In [39]:
len(dfEst[(dfEst['dni'] == '') | (dfEst['dni'] == ' ') | (dfEst['dni'] == 'null') | (dfEst['dni'] == 'none') | (dfEst['dni'] == 'n/a')] )

0

In [5]:
patrones = dfEst['dni'].astype(str).str.replace(r'\d', '#', regex=True)
print(patrones.value_counts())

dni
########      119501
 ########       5317
##.###.###      5182
Name: count, dtype: int64

In [6]:
dfEst['dni'].astype(str).str.strip().str.replace('.', '').str.len().value_counts()

dni
8    130000
Name: count, dtype: int64

In [22]:
conteo_dni = dfEst['dni'].value_counts()
conteo_dni[conteo_dni > 1].value_counts()

count
2    2387
3      81
4       6
Name: count, dtype: int64

### Genero

In [7]:
dfEst.genero.unique()

array(['M', 'F', '1', 'Femenino', 'male', '2', 'm', 'Masculino', 'female',
       'f'], dtype=object)

### Fecha_nacimiento

In [8]:
patronesFecha = dfEst['fecha_nacimiento'].astype(str).str.replace(r'\d', '#', regex=True)
print(patronesFecha.value_counts())

fecha_nacimiento
####-##-##    114462
##/##/####      5129
####            3894
##-##-####      3884
########        2631
Name: count, dtype: int64

* Revisar fechas de nacimiento con solo año

### Nacionalidad

In [9]:
dfEst.nacionalidad.unique()

array(['Argentina', 'Chilena', 'Paraguaya', 'Brasileña', 'Venezolana',
       'Colombiana', 'Boliviana', 'Peruana', nan, 'Uruguaya'],
      dtype=object)

In [10]:
dfEst[dfEst['nacionalidad'].isna()][['id_estudiante', 'nacionalidad']]

        id_estudiante nacionalidad
104               105          NaN
138               139          NaN
197               198          NaN
212               213          NaN
229               230          NaN
...               ...          ...
129837         129838          NaN
129886         129887          NaN
129889         129890          NaN
129937         129938          NaN
129938         129939          NaN

[2736 rows x 2 columns]

* Hay que ver como tratar esto, agregar la clase "No especificado" o asumir que son Argentinos.

### Año ingreso

In [55]:
dfEst.anio_ingreso.unique()

array([2020, 2021, 2022, 2024, 2023])

## Examen:

In [11]:
dfEx.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 890389 entries, 0 to 890388
Data columns (total 6 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   id_examen       890389 non-null  int64
 1   id_inscripcion  890389 non-null  int64
 2   fecha           890389 non-null  object
 3   nota            890389 non-null  float64
 4   numero_intento  890389 non-null  int64
 5   resultado       890389 non-null  object
dtypes: float64(1), int64(3), object(2)
memory usage: 40.8+ MB

* Datos requeridos: id_examen, id_inscripcion, fecha, nota.
* Hay que analizar que hacer con nro_intento, es requerido si o si? asumimos que si viene nulo es el 1ero?

### Fecha

In [12]:
patronesFecha = dfEx['fecha'].astype(str).str.replace(r'\d', '#', regex=True)
print(patronesFecha.value_counts())

fecha
####-##-##    890389
Name: count, dtype: int64

### Nota

In [13]:
len(dfEx[(dfEx['nota']=='') | (dfEx['nota']==' ')])

0

In [18]:
dfEx.nota.max()

10.0

In [19]:
dfEx.nota.min()

1.0

### Nro Intento

In [17]:
dfEx.numero_intento.unique()

array([1, 2, 3])

### Resultado

In [14]:
dfEx.resultado.unique()

array(['Aprobado', 'Desaprobado'], dtype=object)

In [15]:
dfEx[dfEx['resultado'] == 'Desaprobado']['nota'].max()

3.9

In [16]:
dfEx[dfEx['resultado'] == 'Aprobado']['nota'].min()

4.0

* Hay aprobados con nota menor a 0

## Inscripciones:

In [32]:
dfIns.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1003413 entries, 0 to 1003412
Data columns (total 5 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   id_inscripcion     1003413 non-null  int64
 1   id_estudiante      1003413 non-null  int64
 2   id_dictado         1003413 non-null  int64
 3   fecha_inscripcion  1003413 non-null  object
 4   estado             1003413 non-null  object
dtypes: int64(3), object(2)
memory usage: 38.3+ MB

### Fecha Inscripción

In [57]:
patronesFecha = dfIns['fecha_inscripcion'].astype(str).str.replace(r'\d', '#', regex=True)
print(patronesFecha.value_counts())

fecha_inscripcion
####-##-##    1003413
Name: count, dtype: int64

In [34]:
dfIns.fecha_inscripcion.min()

'2023-02-01'

In [35]:
dfIns.fecha_inscripcion.max()

'2024-03-28'

* Las fechas estan en formato ISO

### Estado

In [33]:
dfIns.estado.unique()

array(['Activa', 'Baja', 'Libre'], dtype=object)

In [36]:
dfDic.id_dictado.max()

2261

In [38]:
dfIns.id_dictado.max()

2261

## Dictado:

In [59]:
dfDic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2261 entries, 0 to 2260
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_dictado      2261 non-null   int64
 1   id_curso        2261 non-null   int64
 2   id_docente      2261 non-null   int64
 3   id_programa     2261 non-null   int64
 4   anio_academico  2261 non-null   int64
 5   periodo         2261 non-null   object
 6   turno           2261 non-null   object
 7   aula            2261 non-null   object
 8   cupo_maximo     2261 non-null   int64
dtypes: int64(6), object(3)
memory usage: 159.1+ KB

### Periodo

In [60]:
dfDic.periodo.unique()

array(['C1', 'C2'], dtype=object)

### Turno

In [61]:
dfDic.turno.unique()

array(['Tarde', 'Noche', 'Mañana'], dtype=object)

## Curso:

In [63]:
dfCur.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45 entries, 0 to 44
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_curso           45 non-null     int64
 1   codigo             45 non-null     object
 2   nombre             45 non-null     object
 3   horas_teorica      45 non-null     int64
 4   horas_ejercicios   45 non-null     int64
 5   horas_laboratorio  45 non-null     int64
 6   anio_plan          45 non-null     int64
 7   nivel              45 non-null     int64
dtypes: int64(6), object(2)
memory usage: 2.9+ KB

## Evaluación Curso:

In [65]:
dfEvaCur.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8360 entries, 0 to 8359
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id_evaluacion       8360 non-null   int64
 1   id_dictado          8360 non-null   int64
 2   puntaje_dictado     8360 non-null   int64
 3   puntaje_contenido   8360 non-null   int64
 4   valoracion_general  8360 non-null   int64
dtypes: int64(5)
memory usage: 326.7 KB

## Facultad:

In [66]:
dfFac.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id_facultad  25 non-null     int64
 1   nombre       25 non-null     object
 2   ciudad       25 non-null     object
 3   provincia    25 non-null     object
dtypes: int64(1), object(3)
memory usage: 932.0+ bytes

## Programa:

In [67]:
dfPro.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_programa     50 non-null     int64
 1   nombre          50 non-null     object
 2   tipo            50 non-null     object
 3   duracion_anios  50 non-null     int64
 4   id_facultad     50 non-null     int64
dtypes: int64(3), object(2)
memory usage: 2.1+ KB

In [69]:
dfPro.tipo.unique()

array(['Grado', 'Pregrado'], dtype=object)