In [1]:
import pandas as pd

In [15]:
estudiantes = pd.read_csv('data/dim_estudiante.tsv', sep="\t", encoding="latin1")
examenes = pd.read_csv('data/fact_examen_estudiante.tsv', sep="\t", encoding="latin1")
inscripciones = pd.read_csv('data/fact_inscripcion.tsv', sep="\t", encoding="latin1")
estudiantes.head()
inscripciones.head()

,inscripcion_skey,estudiante_skey,tiempo_skey,dictado_skey,estado,abandono
0,1,117876,20230213,1,Activa,0
1,2,117876,20230203,2,Baja,1
2,3,117876,20240209,4,Activa,0
3,4,117876,20230323,5,Activa,0
4,5,117876,20240321,8,Activa,0

In [14]:
df_fusion = pd.merge(
    estudiantes, inscripciones, on="estudiante_skey", how="left"
)
df_fusion.head()

,estudiante_skey,id_estudiante,dni,nombre,apellido,genero,fecha_nacimiento,nacionalidad,anio_ingreso,edad_ingreso,...,anio_plan_programa,facultad_programa,valid_from,valid_to,es_actual,inscripcion_skey,tiempo_skey,dictado_skey,estado,abandono
0,1,45414,20000016,Gonzalo,Muñoz,M,2001-05-20,Venezolana,2023,22,...,NaN,Facultad Regional Córdoba,2026-05-26,NaN,1,367897.0,20230213.0,472.0,Baja,1.0
1,1,45414,20000016,Gonzalo,Muñoz,M,2001-05-20,Venezolana,2023,22,...,NaN,Facultad Regional Córdoba,2026-05-26,NaN,1,367898.0,20230228.0,463.0,Activa,0.0
2,1,45414,20000016,Gonzalo,Muñoz,M,2001-05-20,Venezolana,2023,22,...,NaN,Facultad Regional Córdoba,2026-05-26,NaN,1,367899.0,20230327.0,493.0,Libre,0.0
3,1,45414,20000016,Gonzalo,Muñoz,M,2001-05-20,Venezolana,2023,22,...,NaN,Facultad Regional Córdoba,2026-05-26,NaN,1,367900.0,20230325.0,475.0,Baja,1.0
4,1,45414,20000016,Gonzalo,Muñoz,M,2001-05-20,Venezolana,2023,22,...,NaN,Facultad Regional Córdoba,2026-05-26,NaN,1,367901.0,20240213.0,482.0,Libre,0.0